name: DrErnesto
favicon: null
layout_spectrum: 0.49309
typography_spectrum: 0.7620900289621204
title: Dr. E
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#076b99'
    - '#61c3e9'
    - '#0000ff'
    - '#0080ff'
    - '#00aaaa'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
