analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.49309
title: Dr. E
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.125
  brandStrength: 0.75
  rhythmicContrast: 0.25
  brandColors:
    - '#076b99'
    - '#61c3e9'
    - '#0000ff'
    - '#0080ff'
    - '#00aaaa'
  lightness: 0.1875
purpose: []
favicon: null
name: DrErnesto
typography_spectrum: 0.7620900289621204
