name: DrErnesto
favicon: null
layout_spectrum: 0.28267856920138
typography_spectrum: 0.7620900289621204
title: Dr. E
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4696069834753871
  lightness: 0.17865113238804042
  saturation: 0.18693914613686502
  rhythmicContrast: 0.494859169004485
purpose: []
